"""Event Planning Agent module."""

from backend.app.event_planning.exceptions import (
    EventPlanningError,
    ValidationError,
    BusinessLogicError,
    DataIntegrityError,
    StorageError,
    # Validation errors
    InvalidUserDataError,
    InvalidGroupDataError,
    InvalidEventDataError,
    InvalidPreferenceDataError,
    InvalidAvailabilityDataError,
    InvalidFeedbackDataError,
    # Business logic errors
    EntityNotFoundError,
    UserNotFoundError,
    GroupNotFoundError,
    EventNotFoundError,
    FeedbackNotFoundError,
    MembershipError,
    AlreadyMemberError,
    NotMemberError,
    NotParticipantError,
    InsufficientAvailabilityError,
    SchedulingConflictError,
    InvalidEventStatusError,
    # Data integrity errors
    DuplicateEntityError,
    OrphanedReferenceError,
    ConcurrentModificationError,
    # Storage errors
    FileStorageError,
)

__all__ = [
    "EventPlanningError",
    "ValidationError",
    "BusinessLogicError",
    "DataIntegrityError",
    "StorageError",
    "InvalidUserDataError",
    "InvalidGroupDataError",
    "InvalidEventDataError",
    "InvalidPreferenceDataError",
    "InvalidAvailabilityDataError",
    "InvalidFeedbackDataError",
    "EntityNotFoundError",
    "UserNotFoundError",
    "GroupNotFoundError",
    "EventNotFoundError",
    "FeedbackNotFoundError",
    "MembershipError",
    "AlreadyMemberError",
    "NotMemberError",
    "NotParticipantError",
    "InsufficientAvailabilityError",
    "SchedulingConflictError",
    "InvalidEventStatusError",
    "DuplicateEntityError",
    "OrphanedReferenceError",
    "ConcurrentModificationError",
    "FileStorageError",
]
